config/routes.rb
Messagedly::Application.routes.draw do
  post 'pusher', to: 'pusher#pusher'

  devise_for :users, :controllers => { :sessions => "api/v1/sessions" }

  authenticated :user do
    scope module: 'backend' do
      root :to => "dashboard#index"
      resources :devices
      resources :tokens
    end
  end

  devise_scope :user do
    namespace :api do
      api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
        resources :messages
        resources :devices
        resources :sessions, :only => [:create, :destroy]
      end
    end
  end

  resources :users

  root :to => redirect('/users/sign_in')

end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	attr_accessible :channel_name
	before_create :generate_access_token
	attr_readonly :access_token
	as_enum :status,  %w{unassigned inactive active}

	protected

	def generate_access_token
		self.access_token = loop do
			random_token = SecureRandom.urlsafe_base64(nil, false)[0..5].upcase
			break random_token unless Device.where(access_token: random_token).exists?
		end
	end
end

app/models/token.rb
class Token < ActiveRecord::Base
  attr_accessible :description, :name
  belongs_to :user
  validates_presence_of :name
  validates_uniqueness_of :name, scope: [:user_id]
  before_create :generate_token

  def short_token
    "#{@attributes["token"].first(5)}..."
  end

  def token
    @attributes["token"]
  end

  private

  def generate_token
    begin
      token = Devise.friendly_token
    end while Token.where(:token => token.to_s).exists?
    self.token = token
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :devices
  has_many :tokens
  
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < InheritedResources::Base
  before_filter :ensure_login
  respond_to :json

  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  protected

    def ensure_login
      unless oauth_access_token
        render json: {errors: ['Missing access token']}, status: :unauthorized, callback: params[:callback]
        return false
      end
      unless current_device
        render json: {errors: ['Invalid access token']}, status: :unauthorized, callback: params[:callback]
        return false
      end
    end

    def current_device
      @current_device ||= Device.from_access_token(oauth_access_token)
    end

    def oauth_access_token
      oauth_access_token ||= (params[:access_token] || oauth_access_token_from_header)
    end


    # grabs access_token from header if one is present
    def oauth_access_token_from_header
      auth_header = request.env["HTTP_AUTHORIZATION"]||""
      match       = auth_header.match(/^token\s(.*)/) || auth_header.match(/^Bearer\s(.*)/)
      return match[1] if match.present?
      false
    end

    def render_404
      render nothing: true, status: 404
    end

    def begin_of_association_chain
      @current_device
    end

end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < Api::V1::BaseController

end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Devise::SessionsController
  respond_to :html, :json
  def create
    respond_to do |format|
      format.html { super }
      format.json {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
        return sign_in_and_redirect(resource_name, resource)
      }
    end
  end

  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(resource, warden.user(scope))
    return render :json => {:success => true, :redirect => stored_location_for(scope) || after_sign_in_path_for(resource), :access_token => warden.user(scope).devices.where(channel_name: params[:device][:uuid]).first_or_create.access_token}
  end

  def failure
    return render:json => {:success => false}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  protect_from_forgery
  layout "dashboard"
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController

  add_breadcrumb "Home", :root_path

  def index

  end
end

app/controllers/backend/devices_controller.rb
class Backend::DevicesController < InheritedResources::Base
  protect_from_forgery
  layout "dashboard"

  add_breadcrumb "Home", :root_path

  add_breadcrumb "Devices", :devices_path

  def create
    device = Device.find_by_access_token params[:device][:access_token]
    unless device.blank?
      device.user = current_user
      device.status = :active
      device.save!
      Pusher.trigger(device.channel_name, 'close_registration', {})
      redirect_to devices_path
    else
      redirect_to new_device_path
    end
  end

  protected

  def begin_of_association_chain
    current_user
  end
end

app/controllers/backend/tokens_controller.rb
class Backend::TokensController < InheritedResources::Base
  protect_from_forgery
  layout "dashboard"

  respond_to :html, :js

  add_breadcrumb "Home", :root_path

  add_breadcrumb "API Tokens", :tokens_path


  def new
    add_breadcrumb "New", :new_token_path
  end

  def create
    create!(:notice => "Nice job creating that token.") { tokens_path }
  end

  def update
    update!(:notice => "Nice job updating that token.") { tokens_path }
  end


  def destroy
    destroy!(:notice => "Nice job deleting that token.") { tokens_path }
  end

  def show
    @token = Token.find params[:id]
    add_breadcrumb "#{@token.name}", token_path(@token)
  end

  protected

  def begin_of_association_chain
    current_user
  end
end

app/controllers/pusher_controller.rb
class PusherController < ActionController::Base

  def pusher
    webhook = Pusher.webhook(request)
    if webhook.valid?
      webhook.events.each do |event|
        case event["name"]
        when 'channel_occupied'
          device = Device.find_or_create_by_channel_name event["channel"]
          unless device.unassigned?
            device.active!
            Pusher.trigger(event["channel"], 'close_registration', {})
          else
            Pusher.trigger(event["channel"], 'unregistered', {:code => device.access_token})
          end
        when 'channel_vacated'
          device = Device.find_by_channel_name event["channel"]
          device.inactive! if device.active?
        end
      end
      render text: 'ok'
    else
      render text: 'invalid', status: 401
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/views/application/_notices.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/backend/dashboard/index.html.erb
<% title "My Dashboard" %>

<!-- Stats start -->
<div class="row">
  <div class="col-md-12">
    <div class="widget">
      <div class="widget-header">
        <div class="title">
          <span class="fs1" aria-hidden="true" data-icon="&#xe098;"></span> Statistics
        </div>
      </div>
      <div class="widget-body">
        <div id="social-stats" style="height:160px"></div>
        <hr>
        <ul class="statistics">
          <li>
            <div class="main-info">
              <a href="#" class="jet-blue-bg" data-original-title="">
                <span class="fs1" aria-hidden="true" data-icon=""></span>
              </a>
              <strong>12,476</strong>
            </div>
            <span>Messages Sent</span>
          </li>
          <li>
            <div class="main-info">
              <a href="#" class="go-green-bg" data-original-title="">
                <span class="fs1" aria-hidden="true" data-icon=""></span>
              </a>
              <strong>2289</strong>
            </div>
            <span>Devices</span>
          </li>
          <li>
            <div class="main-info">
              <a href="#" class="sea-green-bg" data-original-title="">
                <span class="fs1" aria-hidden="true" data-icon=""></span>
              </a>
              <strong><%= current_user.tokens.count %></strong>
            </div>
            <span>API Keys</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Stats end -->

<!-- Row start -->
<div class="row">

  <div class="col-md-6">
    <div class="widget">
      <div class="widget-header">
        <div class="title">
          <span class="fs1" aria-hidden="true" data-icon="&#xe06a;"></span> Recent Messages
        </div>
      </div>
      <div class="widget-body">
        <ul class="comments">
          <li>
            <div class="user pull-left">
              <img src="<%= asset_path('avatar-8.png') %>" alt="user">
            </div>
            <div class="info">
              <div class="name">
                <a href="#">john</a>
              </div>
              <div class="time">
                <i class="icon-time"></i>
                <span>2 min</span>
              </div>
              <small>Lorem ipsum commodo quis.</small>
            </div>
          </li>
          <li>
            <div class="user pull-left">
              <img src="<%= asset_path('avatar-1.png') %>" alt="user">
            </div>
            <div class="info">
              <div class="name">
                <a href="#">Andy</a>
              </div>
              <div class="time">
                <i class="icon-time"></i>
                <span>8 min</span>
              </div>
              <small>Dolor voluptate et in Excepteur.</small>
            </div>
          </li>
          <li>
            <div class="user pull-left">
              <img src="<%= asset_path('avatar-5.png') %>" alt="user">
            </div>
            <div class="info">
              <div class="name">
                <a href="#">Henrik</a>
              </div>
              <div class="time">
                <i class="icon-time"></i>
                <span>17 min</span>
              </div>
              <small>Commodo voluptate et in Excepteur.</small>
            </div>
          </li>
          <li>
            <div class="user pull-left">
              <img src="<%= asset_path('avatar-5.png') %>" alt="user">
            </div>
            <div class="info">
              <div class="name">
                <a href="#">Selva Kumar</a>
              </div>
              <div class="time">
                <i class="icon-time"></i>
                <span>23 min</span>
              </div>
              <small>Terry richardson ex squid.</small>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-sm-6">
    <div class="widget">
      <div class="widget-header">
        <div class="title">
          <span class="fs1" aria-hidden="true" data-icon="&#xe0b3;"></span> Device Statistics
        </div>
      </div>
      <div class="widget-body">
        <ul class="nav nav-tabs no-margin myTabBeauty">
          <li class="active">
            <a data-toggle="tab" href="#designers" data-original-title="">
              <span class="fs1 text-error" aria-hidden="true" data-icon="&#xe196;"></span> Developers
            </a>
          </li>
          <li class="">
            <a data-toggle="tab" href="#managers" data-original-title="">
              <span class="fs1 text-success" aria-hidden="true" data-icon="&#xe06a;"></span> Context
            </a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div id="designers" class="tab-pane fade active in">
            <ul class="developers">
              <li>
                <div class="user pull-left">
                  <img src="<%= asset_path('avatar-8.png') %>" alt="user">
                </div>
                <div class="info">
                  <h6>Johnny</h6>
                  <small>Last Logged In: 08/08/2013 2:21pm</small>
                </div>
              </li>
              <li>
                <div class="user pull-left">
                  <img src="<%= asset_path('avatar-7.png') %>" alt="user">
                </div>
                <div class="info">
                  <h6>John</h6>
                  <small>Last Logged In: 04/19/2013 1:46pm</small>
                </div>
              </li>
              <li>
                <div class="user pull-left">
                  <img src="<%= asset_path('avatar-3.png') %>" alt="user">
                </div>
                <div class="info">
                  <h6>Ruchita</h6>
                  <small>Last Logged In: 05/21/2013 3:54pm</small>
                </div>
              </li>
              <li>
                <div class="user pull-left">
                  <img src="<%= asset_path('avatar-1.png') %>" alt="user">
                </div>
                <div class="info">
                  <h6>Naresh Maddela</h6>
                  <small>Last Logged In: 08/01/2013 6:28pm</small>
                </div>
              </li>
            </ul>
          </div>

          <div id="managers" class="tab-pane fade">
            <h4>Raw denim you</h4>
            <p>
              Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse.
            </p>
            <p class="no-margin">
              Mustache cliche tempor, williamsburg carles vegan helvetica.prehenderit butcher retro keffiyeh dreamcatcher synth. Cosby Reprehenderit butcher retro keffiyeh dreamcatcher synt mi, qui irure terry richardson ex squid.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<!-- Row end -->

</div>

app/views/backend/devices/index.html.erb
<% title "My Devices" %>

<div class="row">
  <div class="col-md-12">

    <div class="widget">
      <div class="widget-body">
        <p class="text-right">
          <a href="<%= new_device_path %>" class="btn btn-success">Add Device</a>
        </p>
        <table class="table table-condensed table-striped table-hover table-bordered pull-left" id="data-table">    
          <thead>
            <tr>
              <th style="width:25%">Device UUID</th>
              <th style="width:10%">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @devices.each do |device| %>
              <tr class="gradeX">
                <td><%= device.channel_name %></td>
                <td>
                  <a href="<%= device_path(device) %>" class="actions-icons">
                    <i class="icon-search"></i>
                  </a>
                  &nbsp;|&nbsp;
                  <a href="<%= edit_device_path(device) %>" class="actions-icons">
                    <i class="icon-edit"></i>
                  </a>
                  &nbsp;|&nbsp;
                  <%= link_to "<i class='icon-trash'></i>".html_safe, device_path(device), method: :delete, class: "delete-row", "data-original-title" => "Delete" %>
                </td>
              </tr>
            <% end %>
            <% if @devices.empty? %>
              <tr>
                <td colspan="4" class="text-center">
                  <i class="icon-lock"></i> You have no devices. Why not <a href="<%= new_device_path %>">Create one now</a>.
                </td>
              </tr>
            <% end %>

          </tbody>
        </table>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

app/views/backend/devices/new.html.erb
<% title "Add Device" %>

<div class="col-md-12">
  <div class="widget">
    <div class="widget-body">
      <%= semantic_form_for Device.new, builder: FormtasticBootstrap::FormBuilder do |f| %>
        <%= f.input :access_token %>
      <% end %>
    </div>
  </div>
</div>

app/views/backend/tokens/_form.html.erb
<%= semantic_form_for @token || Token.new, builder: FormtasticBootstrap::FormBuilder do |f| %>

    <%= f.inputs do %>
      <%= f.input :name, :input_html => { :class => 'form-control'} %>
      <%= f.input :description, :input_html => { :class => 'form-control', :rows => 10} %>
    <% end %>

    <%= f.actions do %>
      <%= f.action :submit, :button_html => { :class => 'btn btn-success'} %>
      <%= f.action :cancel, :as => :link %>
    <% end %>

  <% end %>

app/views/backend/tokens/edit.html.erb
<% title "Edit API Token" %>

<div class="col-md-12">
  <div class="widget">
    <div class="widget-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/backend/tokens/index.html.erb
<% title "My API Tokens" %>

<div class="row">
  <div class="col-md-12">

    <div class="widget">
      <div class="widget-body">
        <p class="text-right">
          <a href="<%= new_token_path %>" class="btn btn-success">New API Token</a>
        </p>
        <table class="table table-condensed table-striped table-hover table-bordered pull-left" id="data-table">    
          <thead>
            <tr>
              <th style="width:25%">Token Name</th>
              <th style="width:35%">Description</th>
              <th style="width:15%">Token</th>
              <th style="width:10%">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @tokens.each do |token| %>
            <tr class="gradeX">
              <td><%= token.name %></td>
              <td><%= truncate(token.description, length: 80, separator: ' ') %></td>
              <td><a href="<%= token_path(token) %>"><%= token.short_token %></a></td>
              <td>
                <a href="<%= token_path(token) %>" class="actions-icons">
                  <i class="icon-search"></i>
                </a>
                &nbsp;|&nbsp;
                <a href="<%= edit_token_path(token) %>" class="actions-icons">
                  <i class="icon-edit"></i>
                </a>
                &nbsp;|&nbsp;
                <%= link_to "<i class='icon-trash'></i>".html_safe, token_path(token), method: :delete, class: "delete-row", "data-original-title" => "Delete" %>
              </td>
            </tr>
            <% end %>
            <% if @tokens.empty? %>
            <tr>
              <td colspan="4" class="text-center">
                <i class="icon-lock"></i> You have no API Tokens. Why not <a href="<%= new_token_path %>">Create one now</a>.
              </td>
            </tr>
            <% end %>

          </tbody>
        </table>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

app/views/backend/tokens/new.html.erb
<% title "New API Token" %>

<div class="col-md-12">
  <div class="widget">
    <div class="widget-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/backend/tokens/show.html.erb
<% title "#{@token.name}" %>
<div class="col-md-12">
	<div class="widget">
		<div class="widget-body">
			<p class="text-right">
				<%= link_to "Delete API Token", token_path(@token), method: :delete, class: "btn btn-danger" %>
			</p>

			<table class="table table-striped table-hover">
				<tbody>
					
					<tr>
						<td style="width:10%;">
							<strong>Name</strong>
						</td>
						<td><%= @token.name %></td>
					</tr>
					<tr>
						<td>
							<strong>State</strong>
						</td>
						<td>
							<span class="label label-success">Active</span>
						</td>
					</tr>
					
					<tr>
						<td>
							<strong>Description</strong>
						</td>
						<td><%= @token.description %></td>
					</tr>
					<tr>
						<td>
							<strong>Created On</strong>
						</td>
						<td><%= @token.created_at.strftime("%Y %b %d") %> <em class="muted">(<%= time_ago_in_words @token.created_at %> ago)</em></td>
					</tr>
					<tr>
						<td>
							<strong>API Token</strong>
						</td>
						<td>
							<span class="text-error"><%= @token.token %></span>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <!--[if lt IE 7]>
    <html class="lt-ie9 lt-ie8 lt-ie7" lang="en">
  <![endif]-->

  <!--[if IE 7]>
    <html class="lt-ie9 lt-ie8" lang="en">
  <![endif]-->

  <!--[if IE 8]>
    <html class="lt-ie9" lang="en">
  <![endif]-->

  <!--[if gt IE 8]>
    <!-->
    <html lang="en">
    <!--
  <![endif]-->

  <head>
    <meta charset="utf-8">
    <title>Messagedly | SMS Through Your Android</title>
    <meta name="author" content="John">
    <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
    <meta name="description" content="Slick Admin Admin UI">
    <meta name="keywords" content="Slick Admin, Admin UI, Admin Dashboard, John">
    
    <script src="js/html5-trunk.js"></script>
    <%= stylesheet_link_tag "bootstrap", :media => "all" %>
    <%= stylesheet_link_tag "main", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>

  <!--[if lt IE 7]>
    <html class="lt-ie9 lt-ie8 lt-ie7" lang="en">
    <![endif]-->

  <!--[if IE 7]>
    <html class="lt-ie9 lt-ie8" lang="en">
    <![endif]-->

  <!--[if IE 8]>
    <html class="lt-ie9" lang="en">
    <![endif]-->

  <!--[if gt IE 8]>
  <!-->
  <html lang="en">
    <!--
    <![endif]-->

    <head>
      <meta charset="utf-8">
      <title>Messagedly | <%= yield(:title) %></title>
      <meta name="author" content="John">
      <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
      <meta name="description" content="Slick Admin Admin UI">
      <meta name="keywords" content="Slick Admin, Admin UI, Admin Dashboard, John">

      <%= stylesheet_link_tag "application", :media => "all" %>
      <%= stylesheet_link_tag "icomoon", :media => "all" %>
      <%= stylesheet_link_tag "main", :media => "all" %>
      <%= csrf_meta_tags %>
    </head>
    <body>

      <!-- Header start -->
      <header>

        <!-- Logo start -->
        <div class="logo">
          M<span>essagedly</span>
        </div>
        <!-- Logo end -->

        <!-- Optional Dropdown start -->
        <div id="optional-dropdown">
          <ul>
            <li>
              <a href="index.html">
                <span class="fs1" aria-hidden="true" data-icon="&#xe000;" ></span>
              </a>
            </li>
            <li>
              <a href="invoice.html">
                <span class="fs1" aria-hidden="true" data-icon="&#xe099;"></span>
                <span class="count-label"></span>
              </a>
              <ul>
                <li>
                  <a href="invoice.html"><span class="fs1" aria-hidden="true" data-icon="&#xe004;"></span> Invoice</a>
                </li>
                <li>
                  <a href="maps.html"><span class="fs1" aria-hidden="true" data-icon="&#xe042;"></span> Maps</a>
                </li>
                <li>
                  <a href="profile.html"><span class="fs1" aria-hidden="true" data-icon="&#xe074;"></span> Profile</a>
                </li>
                <li>
                  <a href="typography.html"> <span class="fs1" aria-hidden="true" data-icon="&#xe141;"></span> Typography</a>
                </li>
                <li>
                  <a href="calendar.html"><span class="fs1" aria-hidden="true" data-icon="&#xe052;"></span> Calendar</a>
                </li>
                <li>
                  <a href="mail.html"><span class="fs1" aria-hidden="true" data-icon="&#xe004;"></span> Messages</a>
                </li>
                <li>
                  <a href="icons.html"><span class="fs1" aria-hidden="true" data-icon="&#xe0a9;"></span> Icons</a>
                </li>
                <li>
                  <a href="grid.html"><span class="fs1" aria-hidden="true" data-icon="&#xe14c;"></span> Grid</a>
                </li>
                <li>
                  <a href="error.html"><span class="fs1" aria-hidden="true" data-icon="&#xe0f4;"></span> 404</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="mail.html">
                <span class="fs1" aria-hidden="true" data-icon="&#xe040;" ></span>
                <span class="count-label"></span>
              </a>
            </li>
          </ul>
        </div>
        <!-- Optional Dropdown end -->

        <!-- Search bar start -->
        <div class="custom-search">
          <input type="text" class="search-query">
          <button> <span class="fs1" aria-hidden="true" data-icon="&#xe07f;"></span></button>
        </div>
        <!-- Search bar end -->

        <!-- Mini navigation start -->
        <div id="mini-nav">
          <ul>
            <li class="hidden-sm">
              <a href="maps.html">Dropdown
                <span class="fs1" aria-hidden="true" data-icon="&#xe099;"></span>
                <span class="count-label">7</span>
              </a>
              <ul>
                <li>
                  <a href="maps.html"><span class="fs1" aria-hidden="true" data-icon="&#xe042;"></span> Maps</a>
                </li>
                <li>
                  <a href="invoice.html"><span class="fs1" aria-hidden="true" data-icon="&#xe004;"></span> Invoice</a>
                </li>
              </ul>
            </li>
            <li class="hidden-sm">
              <a href="maps.html">
                <span class="fs1" aria-hidden="true" data-icon="&#xe042;" ></span>
                <span class="count-label">6</span>
              </a>
              <ul>
                <li>
                  <a href="maps.html"><span class="fs1" aria-hidden="true" data-icon="&#xe042;"></span> Maps</a>
                </li>
              </ul>
            </li>
            <li class="hidden-sm">
              <a href="mail.html">
                <span class="fs1" aria-hidden="true" data-icon="&#xe049;" ></span>
                <span class="count-label">5</span>
              </a>
              <ul>
                <li>
                  <a href="mail.html"><span class="fs1" aria-hidden="true" data-icon="&#xe049;"></span> Messages</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="login.html">
                <span class="text-label">Mr. John </span><span class="fs1" aria-hidden="true" data-icon="&#xe088;"></span>
              </a>
              <ul class="user-summary">
                <li>
                  <div class="summary">
                    <div class="user-pic">
                      <img src="<%= asset_path('avatar-1.png') %>" alt="Slick Admin"/>
                    </div>
                    <div class="basic-details">
                      <h4 class="no-margin">Johnny</h4>
                      <h5 class="no-margin">UX Designer</h5>
                      <small>Garabandha, India</small>
                    </div>
                    <div class="profile-progress">
                      <div class="chart-progress" data-percent="68">
                        68%
                      </div>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </li>
                <li>
                  <%= link_to('Sign Out', destroy_user_session_path, :method => :delete, class: "btn btn-danger pull-right") %>
                  <span class="clearfix"></span>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- Mini navigation end -->

      </header>
      <!-- Header end -->

      <!-- Main Container start -->
      <div class="main-container">

        <!-- Mian navigation start -->
        <div id="mainnav">

          <!-- User pic start -->
          <div class="user-profile-pic">
            <img src="<%= asset_path('avatar-1.png') %>" alt="Slick Admin">
          </div>
          <!-- User pic end -->

          <ul>
            <li class="<%= if params[:controller] == "backend/dashboard" then "active" end %>">
              <%= if params[:controller] == "backend/dashboard" then "<span class='current-arrow'>&nbsp;</span>".html_safe end %>
              <a href="<%= root_path %>">
                <div class="icon">
                  <span class="fs1" aria-hidden="true" data-icon="&#xe0a2;"></span>
                </div>
                Dashboard
              </a>
            </li>
            <li class="<%= if params[:controller] == "backend/tokens" then "active" end %>">
              <%= if params[:controller] == "backend/tokens" then "<span class='current-arrow'>&nbsp;</span>".html_safe end %>
              <a href="<%= tokens_path %>">
                <div class="icon">
                  <span class="fs1" aria-hidden="true" data-icon="&#xe088;"></span>
                </div>
                API Tokens
              </a>
            </li>
            <li class="<%= if params[:controller] == "backend/devices" then "active" end %>">
              <a href="<%= devices_path %>">
                <div class="icon">
                  <span class="fs1" aria-hidden="true" data-icon="&#xe0b8;"></span>
                </div>
                Devices
              </a>
            </li>
            <li>
              <a href="login.html">
                <div class="icon">
                  <span class="fs1" aria-hidden="true" data-icon="&#xe088;"></span>
                </div>
                Logout
              </a>
            </li>
          </ul>
        </div>
        <!-- Main navigation end -->

        <!-- Dashboard wrapper start -->
        <div class="dashboard-wrapper">
          <div class="row page-title">
            <h2>
              <%= yield(:title) %>
              <small>
                <%= render_breadcrumbs :tag => :li, :separator => "<li>/</li>".html_safe %>
              </small>
            </h2>

            <ul class="stats hidden-xs">
              <li class="light-grey-bg">
                <div class="details">
                  <span class="big">$21,345</span>
                  <span class="small">Current Balance</span>
                </div>
              </li>
            </ul>
          </div>

          <%= render "notices" %>


          <%= yield %>

          <!-- Dashboard wrapper end -->

        </div>
        <!-- Main Container end -->


        <!-- Scripts -->

        <%= javascript_include_tag "application" %>

        <script type="text/javascript">
        $(function() {
          $.fn.raty.defaults.path = 'assets';

          $('#rate3').raty({ score: 3 });
          $('#rate5').raty({ score: 5 });
          $('#rate1').raty({ score: 1 });
        });
        </script>
      </body>
      </html>